# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Pricing"
url = "pricing/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
name = "Demo"
url = "demo/"
weight = 4

[[main]]
name = "Documentation"
url = "https://docs.cartfull-shopper.com/docs"
weight = 5

[[main]]
name = "Blog"
url = "https://docs.cartfull-shopper.com/blog"
weight = 6

[[footer_left]]
name = "Pricing"
url = "/pricing"

[[footer_left]]
name = "Documentation"
url = "https://docs.cartfull-shopper.com/docs"

[[footer_left]]
name = "Demo"
url = "/demo"

# footer menu right
[[footer_middle]]
name = "Install Guide"
url = "https://docs.cartfull-shopper.com/docs/guides/install-cartfull-shopper/"

[[footer_middle]]
name = "User Guide"
url = "https://docs.cartfull-shopper.com/docs"

[[footer_middle]]
name = "Privacy Policy"
url = "https://docs.cartfull-shopper.com/privacy/"

[[footer_middle]]
name = "Terms & Conditions"
url = "terms-conditions/"
